# ios_cd.yaml
name: PRODUCTION build

# Controls when the workflow will run
on:
  workflow_dispatch:
concurrency:
  group: prod-$
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  web_build:
    uses: demian-ilnytskyi/workflows/.github/workflows/next_js_build.yml@main
    secrets: inherit
    with:
      FLAVOUR: "production"

